Blog: Deploying Windows FSx joined to an AD using AWS CDK
skyworkz/website pull request #98
Opened 2023-02-26 20:06 UTC by nidhi-s-2903

2023-02-26 20:07 UTC, nidhi-s-2903 commented
Preview Link:
https://feature-blog-windows-fsx-aws-cdk--skyworkz.netlify.app/blog/windows-fsx-joined-to-ad-with-aws-cdk/

2023-02-26 20:44 UTC, bennycornelissen commented
First impression: I'm impressed! Going to give it a more thorough read tomorrow morning because I'm tired now, but this looks pretty much good to go.

I would recommend squashing the commits before we merge though 😉

2023-02-27 06:29 UTC, LFSb approved these changes, later dismissed
Very enjoyable read! Aside from a small suggestion in the first paragraph, I have no further additions. Thanks Nidhi :)

2023-02-27 06:29 UTC, LFSb commented on content/blog/windows-fsx-joined-to-active-directory-using-aws-cdk.md
> +In a Windows Server setup, it is common practice to use Active Directory for server and user management. For this purpose, you can create an AWS managed Active Directory. Any EC2 instances or other r
Suggestion: "In our setup, we required...." should probably be rewritten to "At a client, we had a setup that required...".

2023-02-27 06:34 UTC, LFSb commented on content/blog/windows-fsx-joined-to-active-directory-using-aws-cdk.md
> +In a Windows Server setup, it is common practice to use Active Directory for server and user management. For this purpose, you can create an AWS managed Active Directory. Any EC2 instances or other r
One more addition, maybe link to the https://aws.amazon.com/fsx/ page for people who don't already know what that is 😄

2023-02-27 09:55 UTC, bennycornelissen commented on content/blog/windows-fsx-joined-to-active-directory-using-aws-cdk.md
> +When you create an AD, a security group is automatically assigned to the AD and you cannot assign a different security group to it. In addition to that, you cannot figure out the security group ID af
Tell me there's a bugreport for this.. 🙈

2023-02-27 09:59 UTC, bennycornelissen requested changes
I agree with the suggestions @LFSb made. It's a solid blogpost. I like it. And let's make sure to squash before merging

2023-02-27 20:55 UTC, nidhi-s-2903 commented on content/blog/windows-fsx-joined-to-active-directory-using-aws-cdk.md
> +In a Windows Server setup, it is common practice to use Active Directory for server and user management. For this purpose, you can create an AWS managed Active Directory. Any EC2 instances or other r
Done

2023-02-27 20:55 UTC, nidhi-s-2903 commented on content/blog/windows-fsx-joined-to-active-directory-using-aws-cdk.md
> +In a Windows Server setup, it is common practice to use Active Directory for server and user management. For this purpose, you can create an AWS managed Active Directory. Any EC2 instances or other r
Done

2023-02-28 12:19 UTC, bennycornelissen approved these changes
LGTM 🎉

2023-02-28 12:19 UTC, merged